### PR TITLE
Update edhec.Rd

### PR DESCRIPTION
**Pull request by anshul96go**
Change the link for "About EDHEC Alternative Indexes"

### CODE REVIEW

**Comment by braverock** [comment]
The original URL redirects, but still works.  Why should we apply a change here?

**Comment by joshuaulrich** [comment]
CRAN checks for 301 redirects, and will ask for them to be updated during submission.

**Comment by braverock** [comment]
In that case the proposed patch is also incorrect.  This is not the final URL that the redirect for the original page eventually loads.

I know there has been some discussion about the CRAN redirect check.  This is another case of R core (CRAN) ignoring standards to do things however they like.

**Comment by braverock** [comment]
EDHEC has removed the 301 redirect.  This appears to be the "permanent" URL now.  merging.

**Pull request merged**
