### PR TITLE
Gsoc 2021

### PR DESCRIPTION
**Pull request by jaindhairyahere**
This PR adds the Robust SFM functionality to PerfA!

### CODE REVIEW

**Comment by jaindhairyahere** [comment]
There is a conflict in only the R-CMD-check file, which is I think related to integration with github and is a part of CI/CD pipeline.

**Comment by JustinMShea** [comment]
@jaindhairyahere It appears there are a few errors here picked up by Github actions check. Here is the first:

```
  >     SFM.alpha(managers[,1:3], managers[,8:10], Rf=.035/12) 
       Alpha : SP500 TR Alpha : US 10Y TR Alpha : US 3m TR
  HAM1            0.006             0.009            0.008
  HAM2            0.009             0.011            0.010
  HAM3            0.006             0.010            0.008
  >     SFM.alpha(managers[,1], managers[,8:10], Rf=.035/12, benchmarkCols=F) 
  Error in processResults(result.all, "intercept", Ra.ncols, Rb.ncols, Ra.colnames,  : 
    **F used instead of FALSE**
```

It appears, you need to change the `benchmarkCols=F` to `benchmarkCols=FALSE` 

Please run CMD Check locally in the build tab (if using RStudio) and fix associated errors.

**Comment by JustinMShea** [comment]
@jaymon0703 You may want to review as well :)

**Comment by jaymon0703** [comment]
Thanks @JustinMShea I left a comment [here](https://github.com/braverock/PerformanceAnalytics/pull/180#issuecomment-1277828497)  on the previous PR which was closed. Let us know @jaindhairyahere if you cannot resolve the errors. Not sure about the necessity for solving Warnings and Notes but get the Errors out the way first.

**Pull request closed without merging**
