### PR TITLE
Even charts.RollingRegression panels size

### PR DESCRIPTION
**Pull request by naturalsmen**

### CODE REVIEW

**Comment by rossb34** [comment]
Note that `get_frame()` returns the **current** frame, not the number of frames. Using `get_frame` works ok here because you are calling it at the end so the last frame is the current frame, but understand that this approach will not work in all cases. The length of `asp` must be the same length as `ylim`, both `asp` and `ylim` are used for scaling purposes. A better approach is to get the length of `ylim` and set the `asp` based on that.

What is the logic behind 1/panels and 5/panels for setting the asp?

**Comment by naturalsmen** [comment]
Ross,

I just found that lower limits for y in each panel add up to 1 and the
upper limits add up to 5.  So I divided them by the number of panels, which
are the number of frames divided by 2. That's what I thought.

On Thu, Jun 23, 2016 at 9:28 PM, Ross Bennett <notifications@github.com>
wrote:

> Note that get_frame() returns the *current* frame, not the number of
> frames. Using get_frame works ok here because you are calling it at the
> end so the last frame is the current frame, but understand that this
> approach will not work in all cases. The length of asp must be the same
> length as ylim, both asp and ylim are used for scaling purposes. A better
> approach is to get the length of ylim and set the asp based on that.
>
> What is the logic behind 1/panels and 5/panels for setting the asp?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/braverock/PerformanceAnalytics/pull/51#issuecomment-228049480>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANOV9prOb3DiDLh9OkRLGsUNDBhPI1Mkks5qOooAgaJpZM4I8onO>
> .
>



-- 
GSoC2016-Proposal: https://naturalsmen.shinyapps.io/GSoC2016/

GSoC2016-Timeline:
https://docs.google.com/spreadsheets/d/1FUTc_tT2GqPP7pcdVTgmowWkctPNAUUTfwIdjqMlaJ8/edit?usp=sharing

**Comment by rossb34** [comment]
Eric,

Please clarify what you mean by lower limits for y adding to 1 and upper limits for y add up to 5? The y axis limit, `ylim`, is either set explicitly in a function argument or computed based on the data.

**Comment by naturalsmen** [comment]
Sorry, I didn't recognize it correctly. What I meant is asp settings. After I created three panels and call get_asp, I got a series which looks like 
[1] 0.5 3 0.25 1 0.25 1
I add up 0.5, 0.25 and 0.25 and got 1 in total and I got 5 by adding up 3, 1 and 1. Then I divided them by the number of panels to have the same size.

**Pull request closed without merging**
