### PR TITLE
Even charts.PerformanceSummary panels size

### PR DESCRIPTION
**Pull request by naturalsmen**

### CODE REVIEW

**Comment by rossb34** [comment]
The current charts.PerformanceSummary does not have panels of equal size. I don't think we need to make this change.

**Comment by naturalsmen** [comment]
Ross,
I'm unsure we have the same result. Here is mine. The original function creates this
image
which has unequal panel size.

If the commit is applied, it will create this
image

Did you get the same result or you mean that the panels of the second chart are not equal size?

**Comment by rossb34** [comment]
That is precisely my point, the chart should have unequal panels to match the current stable version. See https://cran.r-project.org/web/packages/PerformanceAnalytics/vignettes/PA-charts.pdf Figure 4.

Note, you probably want to fix the vertical grid lines in your charts so they are not drawn on every day, quarterly or yearly would be more appropriate.

**Comment by naturalsmen** [comment]
Ah, my mistake. You are right. This change is not needed. Thanks for your reminder.

**Pull request closed without merging**
