### PR TITLE
Added ES.SE() which computes the ES estimate and the standard error

### PR DESCRIPTION
**Pull request by chenx26**
This is a major update for the GSoC standard error project with full implementation of the ES.SE() function. ES.SE() function is a wrapper function that contains two main steps. The first step is to call the ES() function in PA package to compute the estimate. The second step is to call the EstimatorES() function to compute the standard error of the ES estimate. The ES.SE() function has additional parameter called "se.method" that to choose how the standard error is calculated. If se.method="none", it returns the same result as calling ES() directly. This ensures backward compatibility. Otherwise, ES.SE() returns a list of two objects, the ES estimate and the Standard Error of the estimate. The ES.SE() function has been tested in the separate package here https://github.com/chenx26/EstimatorStandardError. 

TODO:
- For some reason when I try to build the PA package locally I get the following error message. 
  "Error : package ‘xts’ 0.9.7 was found, but >= 0.10.0 is required by ‘PerformanceAnalytics". But CRAN has only 0.9.7 available. So I was not able to test ES.SE() directly in PA package. Testing in the PA package directly may be desirable.
- If we want complete backward compatibility, we can always change the name of the original ES() to something else (such as ES.raw()) and then name the ES.SE() as the new ES() function. I did not do this because I want the mentors to have the opportunity to go through what is happening and provide comments and suggestions. Ideally, in the final version we will be using the new ES() function with standard error options.

### CODE REVIEW

**Comment by joshuaulrich** [comment]
The GSoC charting refactor project requires the new `plot.xts` from the development version of [xts on GitHub](https://github.com/joshuaulrich/xts). Some of those changes have been merged into PerformanceAnalytics, which is why I increased the version of the xts dependency.

**Comment by chenx26** [comment]
@joshuaulrich 
Thank you very much for the information. Where can I get access to the latest version of xts package? Last I checked, CRAN still only had 0.9.7.

**Comment by braverock** [comment]
The simplest thing for you to do is to install xts from github, e.g.

    require(devtools)
    install_github('joshuaulrich/xts')

**Comment by martinrd** [comment]
Brian and Peter,

The main question is whether you think Xin's approach of starting with a wrapper function, ES.SE in the example, and then ultimately replacing the original function with the function ES obtained by dropping the SE  and have the new ES totally backward compatible. 

NOTE: Xin's serially correlated IF method works really well, beats both Newey-West and the Heidelberger & Welch (1981) frequency domain method.  If you are interested he can send you the relevant part of this PhD General Exam presentation from

Xin, Please clarify if the H2O engine (owned by a company) to compute the generalized linear model for the serially correlated IF method is indeed open source.  If not, then I think it would be necessary to use some other sufficiently good R package, or write R code for the exponential distribution special case of GLM.

**Comment by chenx26** [comment]
@braverock 

Thank you Brian, I am able to build the PA package now.

**Comment by chenx26** [comment]
Hi Brian,

Commit d96b47a corrected a small bug in the previous commit and added all the documentation. The ES.SE() function should be in good shape now.

**Comment by braverock** [comment]
superceded by the RPESE work, closing.

**Pull request closed without merging**
