### PR TITLE
MCA functions

### PR DESCRIPTION
**Pull request by cdries**
This branch implements Moment Component Analysis (MCA) for the coskewness and cokurtosis matrices. MCA is a generalisation of PCA by Lim and Morton (2007) and introduced in finance by Jondeau and Rocking (2017). The functions M3.MCA and M4.MCA implement the methods and return an estimated moment matrix, along with convergence information and the principal components. Documentation is added and references are updated. This code depends on some of the C functions in the sample_m3_m4 branch.

### CODE REVIEW

**Comment by joshuaulrich** [comment]
I just rebased the **MCA** branch on **master** (which now has the history from **sample_m3_m4**) and pushed it to a new branch named **MCA_rebase**.

@cdries you can avoid these weird merges by running `git config --global pull.rebase true` at the command line when you are in the PerformanceAnalytics git directory.

**Comment by cdries** [comment]
Thanks for merging the sample_m3_m4 with master and rebasing the MCA branch. This makes the sample_m3_m4 and MCA branches both redundant since changes in MCA_rebase will be handled directly in this branch and new estimation techniques will be added using a new branch. Is it ok to delete these branches as not to have too many branches?

During next week I will write a test script for the functions in the MCA_rebase branch and post it here. I'll add the methods to the Comoment-vignette and then this branch should be ready to merge in master as well. Before uploading the test script I'll check the MCA_rebase code for any of the pointers you gave earlier in the sample_m3_m4 branch.

**Comment by cdries** [comment]
I checked the code in the MCA_rebase branch and tested it for several inputs. The R script is attached here. The vignette is updated to include the MCA estimator. I only had to change an '&' to '&&' to comply with your previous comments. If you do not have any issues or changes that I should make, then the MCA_rebase branch is ready to be merged with the master branch. The MCA branch can then be deleted.

[test_MCA.R.zip](https://github.com/braverock/PerformanceAnalytics/files/1306186/test_MCA.R.zip)

**Comment by joshuaulrich** [comment]
I've deleted the redundant `sample_m3_m4` and `MCA` branches from the remote repo.  Run `git remote prune origin` to remove them from your local repo.

Thanks for testing and including the test script!

**Comment by joshuaulrich** [comment]
Well, that sucks... I didn't pay attention to which branches this PR was merging.  Deleting the `sample_m3_m4` branch closed this request.

Rest assured, I still have these commits and they will be merged to master.

**Comment by cdries** [comment]
It is ok, the `MCA' branch can be deleted. I only updated the the `MCA_rebase' branch.

**Comment by joshuaulrich** [comment]
These commits were merged as #79.

**Pull request closed without merging**
