### PR TITLE
Fix time series chart based bugs

### PR DESCRIPTION
**Pull request by naturalsmen**
Fix issue #35 and the issue that shading regime created by `chart.TimeSeries` blocks 
the series chart.

### CODE REVIEW

**Comment by braverock** [comment]
As I said in #35, I don't think you can or should remove all the warnings, but I think they need to be changed to only use the hasArg portion of the if test.  As Josh pointed out, any of the arguments to par() should be passed in dots to the plot.xts function.

**Comment by naturalsmen** [comment]
Brian, 
Maybe I am not clear enough. I didn't remove all the warnings. To be more precisely, I *move* them from chart.TimeSeries.base to chart.TimeSeries function. The issue persists if I leave the statement  in chart.TimeSeries.base because chart.TimeSeries which has the deprecated arguments calls chart.TimeSeries.base all the time and I think I could not remove those arguments in chart.TimeSeries. 
For example, from 
chart.TimeSeries <- function(R, auto.grid=TRUE, ...) {
...
  chart.TimeSeries.base(R, auto.grid, ...)
...
}
to
chart.TimeSeries <- function(R, ...) {
...
  chart.TimeSeries.base(R, ...)
...
}
I'll resubmit a pull request to pass the par() arguments to dots later.
Thank you.

**Comment by braverock** [comment]
Thanks for the clarification.  That sounds right.

**Comment by evelynmitchell** [comment]
I don't see where any of the arguments that are throwing 'will be deprecated' arguments, are actually deprecated. And, worse, they are incorrect in pointing towards the docs for more information, which doesn't have any such information.

Do you have a plan in place to do the deprecation, or should you just remove the warnings till you have a release ready which does the deprecation?

**Comment by braverock** [comment]
these were addressed in the larget plotting refactor, so this pull request is stale.  Closing.

**Pull request closed without merging**
