### PR TITLE
Make return.portfolio.arithmetic rebalance according to arguments

### PR DESCRIPTION
**Pull request by jmuhlenkamp**
This PR is a proposed fix with unit test for https://github.com/braverock/PerformanceAnalytics/issues/120

### CODE REVIEW

**Comment by jmuhlenkamp** [comment]
@braverock any thoughts on this?  Thanks!

**Comment by jmuhlenkamp** [comment]
@peterccarl any thoughts on this? I carefully documented the supposed bug here #120 and am happy to rebase to resolve conflicts, etc.  I just need someone to review the documented bug and code and it should be ready to merge.

**Comment by peterccarl** [comment]
Thanks for this.  Unfortunately, we just moved to tinytest from testthat recently.  Could you provide the test conversion?  I appreciate the effort...

**Comment by jmuhlenkamp** [comment]
Thanks for the response.  Yes, I should be able to update test, etc.  May be a few days until I get around to it.  But will tag you again when updated and ready for review.

**Comment by jmuhlenkamp** [comment]
@peterccarl This PR is updated (with a tinytest for the bug that it fixes) and ready for review.  Please let me know if there is anything else I need to do.

**Comment by peterccarl** [comment]
Thank you for the commit - pcc

**Pull request merged**
