### PR TITLE
fixed typo with function parameter name

### PR DESCRIPTION
**Pull request by anandkkumar**

### CODE REVIEW

**Comment by braverock** [comment]
This is in the sandbox, and perhaps @peterccarl should comment, but maybe we could change all instances of Contributions to contributions? not sure why we have a capitalized parameter name here at all.

I don't feel strongly, I'm just asking.   Peter?

**Comment by peterccarl** [comment]
Anand is working on this for me - the original parameters are all 
capitalized, and this is consistent with the rest of the function. I 
went over this with him to day and will accept the pull.

**Comment by anandkkumar** [comment]
I also have unit tests for these methods I would like to contribute. Can this to.period.contributions.R be moved to the R folder and out of sandbox?

**Comment by peterccarl** [comment]
Moved, thanks for sending the tests...

**Pull request merged**
